a = Physician.create(name: "Dr. Strange", specialty: "Mystic Arts")
b = Physician.create(name: "Dr. Kevorkian", specialty: "AS Mastery")
c = Physician.create(name: "Dr. J", specialty: "Urologist")
d = Physician.create(name: "Dr. Robotnik", specialty: "Gynecologist")
e = Physician.create(name: "Dr. Frankenstein", specialty: "Plastic Surgery")
f = Physician.create(name: "Dr. Who", specialty: "Time Travel")
g = Physician.create(name: "Dr. Smith", specialty: "Hand Surgery")
h = Physician.create(name: "Dr. Jacobs", specialty: "Neurology")
i = Physician.create(name: "Dr. Boscov", specialty: "Dermatology")
j = Physician.create(name: "Dr. Buongiorno", specialty: "Paisanologist")
k = Physician.create(name: "Dr. Lee", specialty: "Podiatry")
l = Physician.create(name: "Dr. Long", specialty: "Neurology")
m = Physician.create(name: "Dr. Monet", specialty: "Impressionology")
n = Physician.create(name: "Dr. King", specialty: "")
o = Physician.create(name: "Dr. Frankenstein", specialty: "Plastic Surgery")

p = Patient.create(name: "Daniel Zaltsman")
q = Patient.create(name: "Rachel Lechar")
r = Patient.create(name: "Melissa Assilem")
s = Patient.create(name: "Derek Kered")
t = Patient.create(name: "Ulysses Sessylu")


Appointment.create(physician: a, patient: p, date: "10/11/2019", time: "16:30")
Appointment.create(physician: b, patient: p, date: "10/12/2019", time: "12:30")
Appointment.create(physician: c, patient: q, date: "09/10/2019", time: "13:30")
Appointment.create(physician: d, patient: r, date: "07/12/2021", time: "14:30")
Appointment.create(physician: e, patient: s, date: "09/01/2020", time: "15:30")
Appointment.create(physician: e, patient: s, date: "09/11/2019", time: "11:30")
